### ISSUE TITLE
Комментарий от ментора

### ISSUE THREAD

**Issue by mdwebppua** [nazmariam/nazmariam.github.io#1]
**Визуально** - все отлично.

**Размещение файлов** - корректно нужно картинки чтобы были в папке с картинками, файлы стилей в папке со стилями пример корневой папки: "css (папка), img (папка), index.html"

**Разметка html кода файла index.html:** 
_Структура и расположения тегов хорошо._ 
Как я написал выше картинка должна быть в папке с картинками и картинку 
`<img src="me.jpg" alt="вот она я">` 
нужно было задать в отдельный блок например:
 `<div class="fotoUser"><img src="me.jpg" alt="вот она я"></div>`

**Файл стилей css:**
Как я написал выше файлы css должны быть в папке со стилями.
*_`#content` *_
не нужно было задавать параметр height: 752px; так как если текста будет больше, документ не потянется или задать параметр min-height.
если Вы измерили ширину документа она у вас получилась 513px и Вы задали padding: 50px; значит Вам нужно отнять padding.
margin-left:auto;,margin-right:auto; нужно задать одним параметром margin: 0 auto;
*_`h2` *_ - margin там не нужен.
*_`img` *_ - не правильно делать display: block;,margin: 20px auto; нужно всю картинку поместить в блок как я описал выше и задать в стилях равнение по центру.

**Comment by mdwebppua** [comment]
`<p>содержимое</p>` - если Вы пишите текст то перенос строк не нужно делать снова тегом <p> нужно использовать тег `<br/>` пример:
`<p>Мой контактный телефон<br/> +380660034001</p>`
Так как получаются большие отступы!

**Comment by mdwebppua** [comment]
ЗАЧЕТ

**Comment by nazmariam** [comment]
УРА! Добби свободен!!
